import stylesUrl from "~/styles/index.css";

export function links() {
  return [{ rel: "stylesheet", href: stylesUrl }];
}

export default function Index() {
  return (
    <div className="content">
      <div className="Container">
        <h1>
          CIS105 <span className="rainbow-text">REMIX</span> WebPage
        </h1>
        <div className="intro">
          <p>
            Hello my name is Joe Irvine and welcome to my &nbsp;
            <a href="https://remix.run/">Remix</a>&nbsp; website. Remix is a
            full stack web framework that allows you to focus on the user
            interface and work back through web standards to deliver a fast and
            slick user experience.
          </p>

          <p>
            In this site you'll find some API fetches and a game that was
            created in <a href="https://reactjs.org/">React</a>. The game was
            &nbsp;{" "}
            <a href="https://github.com/TheShonuff/tic-tac-toe">developed</a> by
            me and intergrated into the site using an iframe. The weather
            application was created using a free api from{" "}
            <a href="https://www.weatherapi.com/">WeatherAPI.com.</a> It
            currently only uses the real-time API call that produces current
            weather for any city that you select. The advice generated by the
            Guru comes from{" "}
            <a href="https://api.adviceslip.com/">Advice Slip API</a>. A free
            API with over 10 million pieces of advice.{" "}
          </p>

          <p>
            <a href="https://dadjokes.io/">Dad Jokes</a> are Generated using the
            free tier on <a href="https://rapidapi.com/hub">RapidAPI</a>.
            Currently it only serves 50 jokes per day.{" "}
          </p>
        </div>
        <div className="IndexNav">
          <ul className="IndexList">
            <li className="link-list">
              <a href="/dadjokes" rel="noreferrer">
                Dad Jokes
              </a>
            </li>
            <li className="link-list">
              <a href="/advice" rel="noreferrer">
                Get Advice
              </a>
            </li>
            <li className="link-list">
              <a href="/game" rel="noreferrer">
                Game
              </a>
            </li>
            <li className="link-list">
              <a href="/weather" rel="noreferrer">
                Weather
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}
